version: '3.3'


services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: michelle123
      MYSQL_USER: root
      MYSQL_PASSWORD: michelle123
    volumes:
      - 'dbdata:/var/lib/mysql'
    restart: unless-stopped
    networks:
      - my-network

  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu_service
    volumes:
      - 'dbdata:/app/output'
    networks:
      my-network:
        aliases:
          - ubuntu_service
    depends_on:
      - mariadb

networks:
  my-network:

volumes:
  dbdata:
    driver: local