version: '3.3'


services:

  mariadb_michelle:
    image: linuxserver/mariadb:latest
    container_name: mariadb_michelle
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: michelle123
      MYSQL_USER: root
      MYSQL_PASSWORD: michelle123
    volumes:
      - './dbdata:/config'
    restart: unless-stopped
    networks:
      - my-network

  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu_service
    volumes:
      - './results:/app/output'
    networks:
      my-network:
        aliases:
          - ubuntu_service
    depends_on:
      - mariadb_michelle

networks:
  my-network:
